CREATE TABLE `bc_leads` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(191) NOT NULL,
  `email` varchar(191) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `service_type` varchar(100) DEFAULT NULL,
  `bedrooms` varchar(20) DEFAULT NULL,
  `bathrooms` varchar(20) DEFAULT NULL,
  `went_whatsapp` tinyint(1) NOT NULL DEFAULT 0,
  `scheduled_for` datetime DEFAULT NULL,
  `scheduled_event_sent` tinyint(1) NOT NULL DEFAULT 0,
  `scheduled_event_id` varchar(64) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `fbclid` varchar(255) DEFAULT NULL,
  `gclid` varchar(255) DEFAULT NULL,
  `gbraid` varchar(255) DEFAULT NULL,
  `wbraid` varchar(255) DEFAULT NULL,
  `utm_source` varchar(191) DEFAULT NULL,
  `utm_medium` varchar(191) DEFAULT NULL,
  `utm_campaign` varchar(191) DEFAULT NULL,
  `utm_content` varchar(191) DEFAULT NULL,
  `utm_term` varchar(191) DEFAULT NULL,
  `fbp` varchar(255) DEFAULT NULL,
  `fbc` varchar(255) DEFAULT NULL,
  `page_url` text DEFAULT NULL,
  `referrer` text DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `scheduled_google_ready` tinyint(1) NOT NULL DEFAULT 0,
  `scheduled_google_sent` tinyint(1) NOT NULL DEFAULT 0,
  `paid_value` decimal(10,2) DEFAULT NULL,
  `paid_currency` char(3) DEFAULT 'EUR',
  `paid_at` datetime DEFAULT NULL,
  `purchase_event_sent` tinyint(1) NOT NULL DEFAULT 0,
  `purchase_event_id` varchar(64) DEFAULT NULL,
  `lead_event_id` varchar(64) DEFAULT NULL,
  `estimated_value` decimal(10,2) DEFAULT NULL,
  `went_whatsapp_at` datetime DEFAULT NULL,
  `contact_event_id` varchar(64) DEFAULT NULL,
  `contact_event_sent` tinyint(1) NOT NULL DEFAULT 0,
  `lead_event_sent` tinyint(1) DEFAULT 0,
  `lead_event_response` text DEFAULT NULL,
  `contact_event_response` text DEFAULT NULL,
  `scheduled_event_response` text DEFAULT NULL,
  `purchase_event_response` text DEFAULT NULL,
  `scheduled_value` decimal(10,2) DEFAULT NULL,
  `scheduled_at` datetime DEFAULT NULL,
  `purchase_value` decimal(10,2) DEFAULT NULL,
  `purchase_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
